---
title: "R Notebook"
output: html_notebook
---



```{r}

source("./NFL_Project_Functions.R")


clean_df <- load_clean_data()
```



```{r}

run_check <- check_first_down_features(df=clean_df, play_type_to_check="run")
pass_check <- check_first_down_features(df=clean_df, play_type_to_check="pass")

```


```{r}

# Four columns where first_down_run = 1 but the associated play_type was not a run, rows --> 61423 62038 89327 115396 
# These are likely data entry errors

clean_df[c(62037, 62038, 62039) ,c("play_type","down", "yards_gained", "ydstogo", 
                                   "first_down_rush", "home_field_adv","first_down_pass", "penalty_yards","first_down_penalty")]

clean_df[c(61422, 61423, 61424),]

# 21 Instances where first_down_run=1 but the next play was not a first down. Were some of these the end of a quarter/half/game?
# Rows --> 3366 3993 9430 11472 15993 18120 33828 33886 35673 51445 75518 75540 78753 91937 97328 98886 102296 102483 115431 120780 124930


```




# Shows that the recieving and passing yards columns are redundant, and also require future knowledge
```{r}

# 81818 NA values in receiving_yards
sum(is.na(clean_df[,"receiving_yards"]))

# 81818 NA values in passing_yards
sum(is.na(clean_df[,"passing_yards"]))

# 45836 non-NA values in passing_yards
non_na_passing <- clean_df[!is.na(clean_df[,"passing_yards"]), "passing_yards"]
length(non_na_passing)

# 45836 non-NA values in receiving_yards
non_na_receiving <- clean_df[!is.na(clean_df[,"receiving_yards"]), "receiving_yards"]
length(non_na_receiving)

# 45802 values are the exact same in passing and receiving yards
sum(non_na_passing == non_na_receiving)

# 34 times where passing yards and receiving yards weren't NA, and were different then eachother
misaligned_df <- clean_df[!is.na(clean_df[,"passing_yards"]) & (clean_df[,"passing_yards"] != clean_df[,"receiving_yards"]),]
nrow(misaligned_df)


misaligned_df[,c("down", "quarter_seconds_remaining", "half_seconds_remaining", "game_seconds_remaining", 
                 "receiving_yards", "passing_yards")]

```


# Shows that incomplete_pass and complete_pass require future knowledge
```{r}

# Number of rows where incomplete_pass = 1 --> 23016
nrow(clean_df[clean_df[,"incomplete_pass"] == 1,])


# Number of rows where incomplete_pass = 1 and 
# the current play isn't a pass --> 0
nrow(clean_df[(clean_df[,"incomplete_pass"] == 1) & 
                (clean_df[,"play_type"] != "pass"),])


# Number of rows where incomplete_pass = 1 and 
# the current play isn't a pass --> 0
nrow(clean_df[(clean_df[,"complete_pass"] == 1) & 
                (clean_df[,"play_type"] != "pass"),])

```


# Shows that rushing_yards requires future knowledge
```{r}

# Shows that all plays where rushing_yards isn't NA, the play is a run...
clean_df[!is.na(clean_df[,"rushing_yards"]),c("rushing_yards", "play_type")]

# 52394 plays where rushing_yards is not NA. 
nrow(clean_df[!is.na(clean_df[,"rushing_yards"]),])

# 52394 plays where rushing_yards is not NA and the
# play_type is a run... meaning every time rushing_yards
# is not NA, the play_type is a run play.
nrow(clean_df[!is.na(clean_df[,"rushing_yards"]) & 
                clean_df[,"play_type"]=="run",])


# Another version of the same check above. Shows that amongst all
# plays where rushing_yards is not NA, the only unique play_type 
# is "run"
unique(clean_df[!is.na(clean_df[,"rushing_yards"]), "play_type"])

```



```{r}


```


```{r}


```


```{r}


```

