---
title: "LightGBM"
author: "Braden Anderson"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#devtools::install_github("Microsoft/LightGBM", subdir = "R-package")
#install.packages("lightgbm", repos = "https://cran.r-project.org")
#install.packages("data.table")
#install.packages("jsonlite")

```


```{r cars}

source("./NFL_Project_Functions.R")
library(lightgbm)

clean_df <- load_clean_data()

clean_df <- clean_df[,!(names(clean_df) %in% c("pt_run_props", "pt_pass_props"))]

getwd()
```


```{r}
#devtools::install_github("Microsoft/LightGBM", subdir = "R-package")

dim(clean_df)
```

```{r}

datasets <- get_dataset_splits(df=clean_df)

cv_df <- datasets$cross_validation

dim(cv_df)
```



```{r}
#parameter_grid <- get_default_param_grid()

parameter_grid <- list(boosting=c("gbdt", "dart"),
                       learning_rate=c(0.005, 0.01, 0.1, 0.2),
                       num_rounds=c(250L, 1000L, 1500L), 
                       num_leaves=c(20, 31, 50, 100),
                       min_data_in_leaf=c(10, 20, 30),
                       feature_fraction=c(0.75, 1.0),
                       max_depth=c(-1, 10),
                       extra_trees=c(FALSE))

gs_results <- gridsearch_lightgbm(df=cv_df, 
                                  param_grid=parameter_grid,
                                  base_save_name="./lightgbm_gridsearch",
                                  save_every=20)
```







```{r}
#source("./NFL_Project_Functions.R")

#all_ds <- create_lgb_cv_datasets(df=cv_df, num_folds=5)

#gbdt_train_params = list(objective="binary",
#                         metric="binary_error",
#                         boosting="gbdt",
#                         force_row_wise=TRUE,
#                         learning_rate=0.01,
#                         num_rounds=50L, 
#                         num_leaves=25,
#                         num_threads=5)

#metrics_row <- cross_validate_lgbm(cv_datasets=all_ds, train_params=gbdt_train_params)

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

