---
title: "Project2"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(nflfastR)

source("./NFL_Project_Functions.R")
clean_df <- load_clean_data()


ff <- load_pbp(2018:2021)

# if it's taking too long to load
# library(nflreadr)
# fb <- nflreadr::load_pbp(2018:2021) # 195134 rows, 372 columns

ff <- ff %>% filter(down == 1 | down == 2 | down == 3,
                          play_type == 'run' | play_type == 'pass',
                          season_type == 'REG') %>% 
                  mutate(pos_to = posteam_timeouts_remaining,
                        roof = replace_na(roof, 'retractable'), 
                        wind = replace_na(wind, 0), 
                        temp = replace_na(temp, 75),
                        )
cat_df <- c('play_type', 'pos_to', 'goal_to_go', 'div_game', 'down', 'roof') 
clean_df[cat_df] <- lapply(clean_df[cat_df], as.factor)

remove_id <- grep("_id$", colnames(ff)) # 52 cols
remove_name <- grep("_name$", colnames(ff)) # 43 cols
remove_team <- grep("team", colnames(ff)) # 30
remove_ep <- grep("ep", colnames(ff)) # 26 cols
remove_drive <- grep("^drive_", colnames(ff)) # 17 cols
remove_total <- grep("^total_", colnames(ff)) # 15 cols
remove_x <- grep("x", colnames(ff)) # 12 cols
remove_ko <- grep("kickoff", colnames(ff)) # 9 cols
remove_wp <- grep("_wp", colnames(ff)) # 13 cols; keeps "wp"
remove_punt <- grep("^punt_", colnames(ff)) # 7 cols
remove_fumb <- grep("^fumble", colnames(ff)) # 7 cols
remove_lat <- grep("^lateral_", colnames(ff)) # 5 cols
remove_jersey <- grep("jersey_number$", colnames(ff)) # 4 cols
remove_qb <- grep("^qb_", colnames(ff)) # 5 cols
remove_td <- grep("touchdown", colnames(ff)) # 4 cols
remove_tackle <- grep("tackle", colnames(ff)) # 4 cols
remove_downconv <- grep("down_['c-f']", colnames(ff)) # 4 cols
remove_yards <- grep("yards", colnames(ff)) # 8 cols
remove_first <- grep("^first_", colnames(ff)) # 4 cols
```

```{r}
ff <- ff %>% select(-all_of(remove_id), -all_of(remove_name), -all_of(remove_team), -all_of(remove_ep), -all_of(remove_drive), -all_of(remove_total), -all_of(remove_x), -all_of(remove_ko), -all_of(remove_wp), -all_of(remove_punt), -all_of(remove_fumb), -all_of(remove_lat), -all_of(remove_jersey), -all_of(remove_qb), -all_of(remove_td), -all_of(remove_tackle), -all_of(remove_downconv), -all_of(remove_yards), -all_of(remove_first))

remove_misc <- c('game_date', 'season', 'season_type', 'stadium', 'game_stadium', 'weather', 'id', 'week', 'qtr', 'side_of_field', 'drive', 'sp', 'time', 'start_time', 'time_of_day', 'play_clock', 'quarter_end', 'yrdln', 'ydsnet', 'desc', 'sack', 'touchback', 'no_huddle', 'shotgun', 'complete_pass', 'incomplete_pass', "two_point_attempt", "field_goal_attempt", 'pass_length', 'pass_location', 'run_location', 'run_gap', 'field_goal_result', 'kick_distance', 'two_point_conv_result', 'safety', 'home_timeouts_remaining', 'away_timeouts_remaining', 'timeout', 'score_differential_post', "no_score_prob", "opp_fg_prob", 'opp_safety_prob', "opp_td_prob", "safety_prob", 'two_point_conversion_prob', "defensive_two_point_attempt", "defensive_two_point_conv", 'game_half', 'penalty', 'penalty_type', 'play_deleted', 'aborted_play', 'series_result', 'play_type_nfl', 'st_play_type', 'special', 'rush_attempt', 'pass_attempt', 'series', 'series_success', 'end_clock_time', 'end_yard_line', 'order_sequence', 'away_score', 'home_score', 'location', 'surface', 'result', 'total', 'spread_line', 'success', 'home_coach', 'away_coach', 'rusher', 'receiver', 'passer', 'name', 'pass', 'rush', 'fantasy', 'out_of_bounds', 'play', 'pass_oe', 'cpoe', 'wpa', 'quarter_seconds_remaining')

ff <- ff %>% select(-all_of(remove_misc))

# 127654 rows, 17 columns 
```

```{r}
source("./NFL_Project_Functions.R")

# For loading  clean dataset from .csv
#clean_df <- fread(input="./clean_play_by_play_2018_to_2021.csv.gz", 
#            na.strings=c("NA", ""), 
#            data.table=FALSE           # data.table = FALSE means a data.frame is returned.
#            )


# Function to load 2018-2021 play_by_play data, and save the clean dataset to a .csv.gz file.
clean_df <- load_clean_data()

```

```{r}

head(clean_df)

```



```{r}

sapply(clean_df, class)

```


```{r}

names(clean_df)

```

```{r}
nrow(clean_df)
```



```{r}
length(names(clean_df))
```

```{r}
missing_columns <- sapply(clean_df, function(x) sum(is.na(x)))
missing_columns[missing_columns >  0]
```



```{r}
# CATEGORICAL RESPONSE --> play_type

# NUMERIC VARIABLES
# 1) yardline_100 --> Numeric distance in the number of yards from the opponent's endzone for the posteam.
# 2) ydstogo --> Numeric yards in distance from either the first down marker or the endzone in goal down situations.
# 3) fg_prob -- > Predicted probability of the posteam scoring a FG next.
# 4) td_prob --> Predicted probability of the posteam scoring a TD next.
# 5) wp --> Estimated win probability for the posteam given the current situation at the start of the given play.
# 6) vegaswp --> Estimated win probabiity for the posteam given the current situation at the start of the given play, incorporating pre-game Vegas line.
# 7) cp --> Numeric value indicating the probability for a complete pass based on comparable game situations.
# 8) temp --> The temperature at the stadium only for 'roof' = 'outdoors' or 'open'.(Source: Pro-Football-Reference)
# 9) wind --> The speed of the wind in miles/hour only for 'roof' = 'outdoors' or 'open'. 
# 10) half_seconds_remaining --> Numeric seconds remaining in the half.
# 11) game_seconds_remaining --> Numeric seconds remaining in the game.
# 12) score_differential --> Score differential between the posteam and defteam at the start of the play.

# CATEGORICAL VARIABLES
# 13) goal_to_go --> Binary indicator for whether or not the posteam is in a goal down situation.
# 14) div_game -->
# 15) roof --> 
# 16) down --> 
```


```{r}
library(gridExtra)

p0 <- plot_categorical_proportions(df=clean_df, categorical_predictor="goal_to_go")+ggtitle("Proportion of Pass Plays based on Level of 'Goal to Go'") + scale_x_discrete("Goal to Go") + scale_y_continuous("Proportion of Pass Plays")
p0
```


```{r}
p1 <- plot_categorical_proportions(df=clean_df, categorical_predictor="div_game")+ggtitle("Proportion of Pass Plays Between Non/ Divisional Games") + scale_x_discrete("Divisional Game") + scale_y_continuous("Proportion of Pass Plays")
p1
```



```{r}
p2 <- plot_categorical_proportions(df=clean_df, categorical_predictor="roof")+ggtitle("Proportion of Pass Plays for Roof Type") + scale_x_discrete("Roof") + scale_y_continuous("Proportion of Pass Plays")
p2
```


```{r}
p3 <- plot_categorical_proportions(df=clean_df, categorical_predictor="down")+ggtitle("Proportion of Pass Plays for Level of Down") + scale_x_discrete("Down") + scale_y_continuous("Proportion of Pass Plays")
p3

grid.arrange(p0,p1,p2,p3)
```


```{r, fig.height=5, fig.width=15}


plot_histogram_by_target_level(continuous_variable="yardline_100", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_left",
                                    summary_table_loc = "upper_left", 
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```



```{r, fig.height=5, fig.width=15}


plot_histogram_by_target_level(continuous_variable="ydstogo", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```


```{r, fig.height=5, fig.width=15}


plot_histogram_by_target_level(continuous_variable="fg_prob", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_left",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```


```{r, fig.height=5, fig.width=15}

plot_histogram_by_target_level(continuous_variable="td_prob", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_left",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```


```{r, fig.height=5, fig.width=15}


p <- plot_histogram_by_target_level(continuous_variable="wp", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right",
                                    summary_table_loc = "upper_left",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```

```{r, fig.height=5, fig.width=15}

p <- plot_histogram_by_target_level(continuous_variable="temp", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right",
                                    summary_table_loc = "upper_left",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```


```{r, fig.height=5, fig.width=15}

p <- plot_histogram_by_target_level(continuous_variable="wind", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```


```{r, fig.height=5, fig.width=15}

p <- plot_histogram_by_target_level(continuous_variable="score_differential", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```

```{r, fig.height=5, fig.width=15}

p <- plot_histogram_by_target_level(continuous_variable="half_seconds_remaining", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right",
                                    num_bins_left=200,
                                    num_bins_right=200, 
                                    round_digits=5)

```


```{r, fig.height=5, fig.width=15}

p <- plot_histogram_by_target_level(continuous_variable="game_seconds_remaining", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```




```{r, fig.height=5, fig.width=15}


p <- plot_histogram_by_target_level(continuous_variable="pt_pass_props", 
                                    df=clean_df, 
                                    test_type="welches_t", 
                                    means_table_plot="Left", 
                                    means_test_table_loc="upper_right", 
                                    summary_table_plot="Right", 
                                    summary_table_loc="upper_left",
                                    num_bins_left=50,
                                    num_bins_right=50, 
                                    round_digits=5)

```

# EDA: Categorical
```{r}
# play_type
table(clean_df$play_type) # count of each play_type

clean_df %>% ggplot(aes(x=play_type, fill=play_type)) + geom_bar(position = 'dodge') + theme_minimal()

# down. possible correlation with score_differential esp on 3rd down?
table(clean_df$down) # count of each level
xtabs(~play_type+down, data=clean_df) # count of level and play_type

clean_df %>% ggplot(aes(x=down, fill=play_type)) + 
          geom_bar(position = 'dodge') + theme_minimal() # count
clean_df %>% ggplot(aes(x=down, fill=play_type)) + 
          geom_bar(aes( y=..count../tapply(..count.., ..x.. ,sum)[..x..]), position="dodge") + 
          theme_minimal() # porportion (pass and run of down == 1 will sum to 1)

# pos_to
table(clean_df$pos_to) # count of time outs by possession team
xtabs(~play_type+pos_to, data=clean_df) # count of timeouts per play_type

clean_df %>% ggplot(aes(x=pos_to, fill=play_type)) + 
          geom_bar(position = 'dodge') + 
          theme_minimal() # count
clean_df %>% ggplot(aes(x=pos_to, fill=play_type)) + 
          geom_bar(aes( y=..count../tapply(..count.., ..x.. ,sum)[..x..]), position="dodge") + 
          theme_minimal() # proportion (pass and run of pos_to == 0 will sum to 1) #this one doesn't work

# goal_to_go
table(clean_df$goal_to_go)
xtabs(~play_type+goal_to_go, data=clean_df)

clean_df %>% ggplot(aes(x=goal_to_go, fill=play_type)) + 
            geom_bar(position = 'dodge') + 
            theme_minimal() # count
clean_df %>% ggplot(aes(x=goal_to_go, fill=play_type)) + 
            geom_bar(aes( y=..count../tapply(..count.., ..x.. ,sum)[..x..]), position="dodge") + 
            theme_minimal() # proportion (pass + run of goal_to_go == 0 will sum to 1)

# roof
table(clean_df$roof)
xtabs(~play_type+roof, data=clean_df)

clean_df %>% ggplot(aes(x=roof, fill=play_type)) + 
            geom_bar(position = 'dodge') + theme_minimal() # count
clean_df %>% ggplot(aes(x=roof, fill=play_type)) + 
            geom_bar(aes( y=..count../tapply(..count.., ..x.. ,sum)[..x..]), position="dodge") + 
            theme_minimal() # prop (pass + run of roof == closed will sum to 1)

# div_game
table(clean_df$div_game)
xtabs(~play_type+div_game, data=clean_df)

clean_df %>% ggplot(aes(x=div_game, fill=play_type)) + 
            geom_bar(position = 'dodge') + 
            theme_minimal() # count
clean_df %>% ggplot(aes(x=div_game, fill=play_type)) + 
            geom_bar(aes( y=..count../tapply(..count.., ..x.. ,sum)[..x..]), position="dodge") + 
            theme_minimal() # proportion (pass + run of div_game == 0 will sum to 1)
```

# EDA: Numerical
```{r}
# score_differential
c0<-clean_df %>% ggplot(aes(x=score_differential, fill=play_type)) + 
        geom_histogram(aes(y=..count..), alpha=.5) + 
        theme_minimal() # histogram
c1<-clean_df %>% ggplot(aes(x=score_differential, fill=play_type)) + 
          geom_density(aes(y=..count..), alpha=.5) + 
          theme_minimal() # density count
c2<-clean_df %>% ggplot(aes(x=score_differential, fill=play_type)) + 
        geom_density(alpha=.5) + 
        theme_minimal() # by density
c3<-clean_df %>% ggplot(aes(x=score_differential, fill=play_type)) + 
        geom_boxplot(alpha=.5) + 
        theme_minimal() # boxplot

grid.arrange(c0,c1,c2,c3)

## yardline_100
c4<-clean_df %>% ggplot(aes(x=yardline_100, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal() # histogram
c5<-clean_df %>% ggplot(aes(x=yardline_100, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal() # density
c6<-clean_df %>% ggplot(aes(x=yardline_100, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal() # boxplot

grid.arrange(c4,c5,c6)


## ydstogo
c7<-clean_df %>% ggplot(aes(x=ydstogo, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal() # histogram
c8<-clean_df %>% ggplot(aes(x=ydstogo, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal() # density
c9<-clean_df %>% ggplot(aes(x=ydstogo, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal() # boxplot

grid.arrange(c7,c8,c9)

## fg_prob
c10<-clean_df %>% ggplot(aes(x=fg_prob, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal()
c11<-clean_df %>% ggplot(aes(x=fg_prob, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal()
c12<-clean_df %>% ggplot(aes(x=fg_prob, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal()

grid.arrange(c10,c11,c12)

## td_prob. good predictor
c13<-clean_df %>% ggplot(aes(x=td_prob, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal()
c14<-clean_df %>% ggplot(aes(x=td_prob, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal()
c15<-clean_df %>% ggplot(aes(x=td_prob, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal()

grid.arrange(c13,c14,c15)


## wp
c16<-clean_df %>% ggplot(aes(x=wp, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal()
c17<-clean_df %>% ggplot(aes(x=wp, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal()
c18<-clean_df %>% ggplot(aes(x=wp, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal()

grid.arrange(c16,c17,c18)


## temp
c19<-clean_df %>% ggplot(aes(x=temp, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal()
c20<-clean_df %>% ggplot(aes(x=temp, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal()
c21<-clean_df %>% ggplot(aes(x=temp, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal()

grid.arrange(c19,c20,c21)


## wind
c22<-clean_df %>% ggplot(aes(x=wind, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal()
c23<-clean_df %>% ggplot(aes(x=wind, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal()
c24<-clean_df %>% ggplot(aes(x=wind, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal()

grid.arrange(c22, c23, c24)

## half_seconds_remaining
c25<-clean_df %>% ggplot(aes(x=half_seconds_remaining, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal()
c26<-clean_df %>% ggplot(aes(x=half_seconds_remaining, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal()
c27<-clean_df %>% ggplot(aes(x=half_seconds_remaining, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal()

grid.arrange(c25,c26,c27)

## game_seconds_remaining
c28<-clean_df %>% ggplot(aes(x=game_seconds_remaining, fill=play_type)) + 
          geom_histogram(alpha=.5) + 
          theme_minimal()
c29<-clean_df %>% ggplot(aes(x=game_seconds_remaining, fill=play_type)) + 
          geom_density(alpha=.5) + 
          theme_minimal()
c30<-clean_df %>% ggplot(aes(x=game_seconds_remaining, fill=play_type)) + 
          geom_boxplot(alpha=.5) + 
          theme_minimal()

grid.arrange(c28,c29,c30)
```

# Split data
```{r}
library(splitTools)
index <- partition(clean_df$play_type, p = c(train = 0.8, test = 0.1, valid = 0.1), seed = 42) 
train <- clean_df[index$train, ]
test <- clean_df[index$test, ]
valid <- clean_df[index$valid, ]
```

# Logistic Regression: Simple

Model with full data:
```{r}
simple.mod.full <- glm(play_type~., family = binomial, data=clean_df)
summary(simple.mod.full)
pred <- predict(simple.mod.full, clean_df, type = 'response')

```

# Logistic Regression: Complex
```{r}

```

# PCA 1- don't use this
```{r}
library(ISLR)
library(gplots)
library(ggplot2)

X <- train[,c('yardline_100', 'game_seconds_remaining', 'ydstogo', 'score_differential', 'fg_prob', 'td_prob', 'wp')] #temp, wind, and pos_to could be categorical variables so excluding for now
#102123 values, 7 predictors

X <- as.matrix(X) #easier to transpose versus DF's

pca <- prcomp(X, scale. = TRUE) #Scale= TRUE given covariates like game_seconds have such large numbers
pca$sdev #representing SD of covariates

summary(X)

z <-pca$sdev
plot(1:7, z) #when scaling, you'll notice more PC's show variance versus not scaling (only 1 and 2 PC's)

plot(1:7, z^2/sum(z^2)) #Scree plot- variance by each features
plot(1:7, cumsum(z^2/sum(z^2))) #Total/aggregate variance by no. of features

cumsum(z^2/sum(z^2)) #1st 4 to 5 PC's will account for 90% of the variance- 85% for 4, 80% for 5

pca$rotation
#PC1= TD Scoreability, yardline_100 is inversely correlated to td_prob- TD prob goes up when yard line goes down
#PC2= Gloating (score differential)
#PC3= Desperation(Time remaining)
#PC4= PathofLeastResistance (YdstoGo)...
#PC8= Score differential versus wp (score differential behind signals lower win probability)- were there no observations of high score differentials?

pca$center #average value of each dimension from predictor data- ex: team with ball was at 49yds out of 100, score_differential: possession team had lead by 1.5 pts, fg_prob 25.7% probability of fg score

pca$scale #standard deviations after 0 centered and scaled as accounted for in line 571

head(pca$x) #take this to regression algorithms

plot(PC2~PC1, data=pca$x)

ggplot(data = X, aes(x = PC1, y = PC2)) +
  geom_point(aes(col=play_type), size=1)+
  ggtitle("PCA of Play Type")

#if want to do complete  cases only: 
#raw
#wd= raw[complete.cases(raw),] #subsetting with removal of NA's
```
#PCA 2- use this
```{r}
install.packages("contourPlot")
library(contourPlot)
library(MASS)
library(caret)
library(mlbench)

#Dataframe set to compare PC's
X0 <- train[,c('yardline_100', 'game_seconds_remaining', 'ydstogo', 'score_differential', 'fg_prob', 'td_prob', 'wp', 'temp', 'wind', "play_type")]

X1 <- train[,c('yardline_100', 'game_seconds_remaining', 'ydstogo', 'score_differential', 'fg_prob', 'td_prob', 'wp', 'temp', 'wind')] #temp, wind, and pos_to could be categorical variables so excluding for now
#find total values, 9 predictors

X2  <- test[,c('yardline_100', 'game_seconds_remaining', 'ydstogo', 'score_differential', 'fg_prob', 'td_prob', 'wp', 'temp', 'wind')]

X1 <- as.matrix(X1) #easier to transpose versus DF's
X2 <- as.matrix(X2)

#pca1 <-prcomp(X1) #no scale
pca1 <- prcomp(X1, scale. = TRUE) #Scale= TRUE given covariates like game_seconds have such large numbers
pca1$sdev #representing SD of covariates

#code in case need to use df versus matrix
pca0<-pca1$x
pca0<-data.frame(pca0)

pca2 <- prcomp(X2, scale. = TRUE)

summary(X1)

z1 <-pca1$sdev

#par(mfrow=c(1,2)) #used to show pre-scale and scale
#plot(1:9, z1, main="Scree Plot PC's prior to scaling", xlab= "PC's", ylab="Prop. Var. Explained") #pre-scaling
plot(1:9, z1) #when scaling, you'll notice more PC's show variance versus not scaling (only 1 and 2 PC's)

##overlay two plots
l1<- plot(1:9, z1^2/sum(z1^2),type='l',main="Scree Plot PC's",xlab= "PC's", ylab="Prop. Var. Explained",ylim=c(0,1)) #Scree plot- variance by each features
#l2<- plot(1:9, cumsum(z1^2/sum(z1^2)),type='b',main="Total/Aggregate Variance by No. of Features",xlab= "PC's", ylab="Prop. Var. Explained",ylim=c(0,1)) #Total/aggregate variance by no. of features; don't need to run this 
#1st 5 will account for ~85% of the variance; keep 5
lines(1:9, cumsum(z1^2/sum(z1^2)), type='b', col='blue', lty= 1, pch=20, lwd=1)

cumdf<-cumsum(z1^2/sum(z1^2)) 
cumsum(z1^2/sum(z1^2)) #Cumulative Proportion
plot(1:9,cumdf,type="l",main="Cumulative proportion", xlab="PC's", ylab= "Prop. Var. Explained", ylim=c(0,1))
#1st 5 will account for ~85% of the variance; keep 5

lab_to_col = function (labels){
cols = rainbow (length(unique(labels)))
cols[as.numeric (as.factor(labels))]
}

par(mfrow=c(1,2))

l1<-plot(pca1$x[,1], pca1$x[,2], col = lab_to_col(X0$play_type), pch = 20, xlab = 'PC1', ylab='PC2')
l2<-plot(pca1$x[,4], pca1$x[,5], col = lab_to_col(X0$play_type), pch = 20, xlab = 'PC4', ylab='PC5')
mtext("Comparison of PC 1 & 2 vs 4 & 5", side= 3, line= -2, outer=TRUE, cex.main= 1.5)

library(plotly)

pca1$rotation #look for values on same side of 0
#PC1= TD Scoreability, yardline_100 is inversely correlated to td_prob- TD prob goes up when yard line goes down
#PC2= Gloating (score differential & wp)
#PC3= Climate: Wind & Temp are most dominant features in 3rd most important thing
#PC4= KickIt: (YdstoGo v fg_prob)...
#PC5= Distance strategy(Game_seconds_remaining + ydstogo)
#PC6= ??

pca1$center

pca1$scale

head(pca1$x) #take this to regression algorithms

#based on our findings PCA/scatterplot matrix of separation/disparity doesn't bring a lot of value for EDA- this is due to low # of predictors being used to start

```

#LDA versus QDA
```{r}
#LDA
library(ROCR)

dx<-data.frame(as.data.frame(pca2$x[,1:8])) #decided on 8 predictors after running permutations of PC's
dx$play_type=test$play_type
mod<-lda(play_type ~., data=dx) #creating model for LDA

#confusion matrix
pred<-predict(mod, newdata=dx)$class
t<-table(pred=pred,actual=test$play_type) #correct ~50K passes, run ~11, incorrect about 40K altogether (prediction was pass (30K) and it was a run)
t

acc<- (t[1,1] + t[2,2])/sum(t) #accuracy
acc

gmaAcc<-(t[1,1]+t[2,1])/sum(t) #pass play summary
gmaAcc

#ROC
modPred<-predict(mod, newdx=dx)$posterior
modPred
modPred2<-modPred[,2]
modPred2

predR <- prediction(modPred2, dx$play_type)
roc.perf = performance(predR, measure = "tpr", x.measure = "fpr")
auc.test <- performance(predR, measure = "auc")
auc.test <- auc.test@y.values

par(mfrow=c(1,2))

#Plot ROC
plot(roc.perf,main="LDA")
abline(a=0, b= 1) #Ref line indicating poor performance
text(x = .40, y = .6,paste("AUC = ", round(auc.test[[1]],3), sep = ""))

#QDA
modQ<-lda(play_type ~., data=dx) #creating model for QDA

predQ<-predict(modQ, newdata=dx)$class
tQ<-table(pred=predQ,actual=test$play_type) #very nominal accuracy improvement- one addl pass prediction improvement
tQ

accQ<- (tQ[1,1] + tQ[2,2])/sum(tQ) #accuracy
accQ 

#ROC- QDA
modPredQ<-predict(mod, newdx=dx1)$posterior
modPredQ
modPredQ2<-modPred[,2]
modPredQ2

predRQ <- prediction(modPredQ2, dx$play_type)
roc.perf1 = performance(predRQ, measure = "tpr", x.measure = "fpr")
auc.test1 <- performance(predRQ, measure = "auc")
auc.test1 <- auc.test1@y.values

#Plot ROC- QDA
plot(roc.perf1,main="QDA")
abline(a=0, b= 1) #Ref line indicating poor performance
text(x = .40, y = .6,paste("AUC = ", round(auc.test1[[1]],3), sep = ""))

```

# Nonparametric 
```{r}

```

```{r}
library(randomForest)
library(vita)

perm_imp <- vita::PIMP(X=clean_df[,(names(clean_df) != "play_type")], 
                       y=clean_df[,"play_type",],
                       rForest=randomForest::randomForest(formula=play_type~.,
                                                          data=clean_df, 
                                                          importance=TRUE),
                       S=100,
                       parallel=TRUE,
                       ncores=5,
                       seed=42)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
