---
title: "Summary_Stats"
author: "Braden Anderson"
date: '2022-04-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
source("./NFL_Project_Functions.R")
library(arsenal)
```


```{r}
df <- load_clean_data(remove_run_props = FALSE, remove_pass_props = FALSE)

head(df)
```



# Dataframe for creating tables of just the numeric features
```{r}
numeric_df <- df[,!(sapply(df, is.factor))]

numeric_df[,"play_type"] <- df[,"play_type"]

```



```{r}

# Tables seemed to look better when you didn't try to put too many features in a single table.
# So I broke up the numeric features into a couple different tables.


mycontrols  <- tableby.control(test=FALSE, 
                               total=TRUE,
                               numeric.test="kwt", cat.test="chisq",
                               numeric.stats=c("range", "median", "meansd","q1q3"),
                               cat.stats=c("countpct"),
                               stats.labels=list(Range='range', MeanSD="meansd", median='Median', q1q3='Q1,Q3'))

numeric_table <-  arsenal::tableby(formula = play_type~., 
                                   data=numeric_df[,(names(numeric_df) %in% c("play_type","yardline_100", "ydstogo", "score_differential", "game_seconds_remaining"))], 
                                   control=mycontrols)

summary(numeric_table)
```



```{r}

# Table for some of the numeric features not included above.

numeric_table <-  arsenal::tableby(formula = play_type~., 
                                   data=numeric_df[,(names(numeric_df) %in% c("play_type","temp", "wind", "pt_run_props", "pt_pass_props"))], 
                                   control=mycontrols)

summary(numeric_table)

```



```{r}

# Table for the rest of the numeric features

numeric_table <-  arsenal::tableby(formula = play_type~., 
                                   data=numeric_df[,(names(numeric_df) %in% c("play_type","wp", "fg_prob", "td_prob"))], 
                                   control=mycontrols)

summary(numeric_table)
```




```{r}

# Dataframe containing only the factor columns
factor_df <- df[,(sapply(df, is.factor))]


# Table of the factor columns
factor_table <-  arsenal::tableby(formula = play_type~., 
                                   data=factor_df, 
                                   control=mycontrols)

summary(factor_table)

```


